#!/bin/bash
iptables -t filter -F
iptables -t nat -F
iptables -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -s "{{vpn_lan}}/{{vpn_lan_mask}}" -j ACCEPT
iptables -A FORWARD -j REJECT
iptables -t nat -A POSTROUTING -s "{{vpn_lan}}/{{vpn_lan_mask}}" -j MASQUERADE
